[package]
name = "NameService"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
name_service = "0xfa5F07319724580eF16DCEF6Ce4d3b0BD0348E48"

[dev-addresses]
name_service = "0x2"

[dependencies]
InitiaStdlib = { local = "../../../initia/initiavm/crates/stdlib/src/initia_stdlib" }
