[package]
name = "Usernames"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
usernames = "0x72ed9b26ecdcd6a21d304df50f19abfdbe31d2c02f60c84627844620a45940ef"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }
