[package]
name = "Usernames"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
usernames = "0x42cd8467b1c86e59bf319e5664a09b6b5840bb3fac64f5ce690b5041c530565a"
pair = "_"

[dev-addresses]
pair = "0x892d79399f244a7fe7273c27ece2b5c36024131565fcd331fc3dc9c480add001"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }
