[package]
name = "Usernames"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
usernames = "_"
lp_publisher = "_"

[dev-addresses]
usernames = "0x2"
lp_publisher = "0x3"

[dependencies]
InitiaStdlib = { local = "../../backends/initiavm/precompile/modules/initia_stdlib" }
