[package]
name = "NameService"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
name_service = "_"

[dev-addresses]
name_service = "0x2"

[dependencies]
InitiaStdlib = { local = "../../backends/initiavm/crates/stdlib/src/initia_stdlib" }
